"""
Constants for the Home Assistant backend.
"""
EMPTY_STRING = ""
DOUBLE_SLASH = "//"

PROTO = "ws://"
PROTO_SSL = "wss://"

STATE = "state"
ATTRIBUTES = "attributes"

CONNECTED = "Connected"
CONNECTING = "Connecting"
DISCONNECTING = "Disconnecting"
NOT_CONNECTED = "Not connected"
AUTHENTICATING = "Authenticating"
WAITING_FOR_RETRY = "Waiting for retry"

HA_CONNECTED = "connected"

HASS_WEBSOCKET_API = "/api/websocket?latest"

AUTH_REQUIRED = "auth_required"
AUTH = "auth"
ACCESS_TOKEN = "access_token"
AUTH_OK = "auth_ok"
AUTH_ERROR = "Could not auth with Home Assistant"
GET_CONFIG = "get_config"
GET_STATES = "get_states"
GET_SERVICES = "get_services"
RUNNING = "RUNNING"
ERROR_NOT_STARTED = "Home Assistant not fully started - retrying"
ERROR_SEND = "Cannot send message: {}"
ERROR_GENERIC = "An error occurred: {}"
ERROR_PARSE = "Could not parse message: {}"
ERROR_STATES = "Error retrieving states: {}"
ERROR_SERVICES = "Error retrieving services: {}"
INFO_CONNECTED = "Connected to Home Assistant"
INFO_DISCONNECTED = "Disconnected from Home Assistant"
WARNING_NOT_SUBSCRIBED = "Received event for entity {} but not subscribed to it."
FIELD_EVENT = "event"
ENTITY_ID = "entity_id"
ID = "id"
FIELD_TYPE = "type"
FIELD_SUCCESS = "success"
FIELD_RESULT = "result"
FIELD_ERROR = "error"
BUTTON_ENCODE_SYMBOL = "-"
RECONNECT_INTERVAL = 10
ACTIONS = "actions"
VARIABLES = "variables"
SUBSCRIPTION_ID = "subscription_id"
TRIGGER = "trigger"
TO_STATE = "to_state"
FROM_STATE = "from_state"
DOT = "."
NA = "N/A"
OFF = "off"
CALL_SERVICE = "call_service"
DOMAIN = "domain"
SERVICE = "service"
TARGET = "target"
SERVICE_DATA = "service_data"
SUBSCRIBE_TRIGGER = "subscribe_trigger"
UNSUBSCRIBE_EVENTS = "unsubscribe_events"
PLATFORM = "platform"

CERT_REQS = "cert_reqs"